services:
    mysql:
        image: 'mysql:latest'
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_USER: 'root'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
